### ISSUE TITLE
Error ECONNREFUSED 127.0.0.1:6000

### ISSUE THREAD

**Issue by ghost** [enspiral-root-systems/catstack#59]
`11:57:19 GMT+0100 (CET) [HMR] Emitting updates
Error: connect ECONNREFUSED 127.0.0.1:6000
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)
Error: socket hang up
    at createHangUpError (_http_client.js:206:15)
    at Socket.socketCloseListener (_http_client.js:238:23)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)`

after a npm run dev, if I edit a componnent, and then refresh the browser. 
I had to close and re run to fix it

**Comment by ahdinosaur** [comment]
hey @naptiv, does https://github.com/enspiral-craftworks/business-stack/pull/63 fix this issue for you?

**Comment by ahdinosaur** [comment]
stale, no longer maintaining `catstack@1`
